name: learning_text_recognition
description: The easy way to use ML Kit for text recognition in Flutter.
version: 0.0.3
# author: Salman S
homepage: https://github.com/salkuadrat/learning/tree/master/packages/learning_text_recognition
repository: https://github.com/salkuadrat/learning/tree/master/packages/learning_text_recognition

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  learning_input_image: ^0.0.6+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.salkuadrat.learning.learning_text_recognition
        pluginClass: LearningTextRecognitionPlugin
      ios:
        pluginClass: LearningTextRecognitionPlugin
